config/routes.rb
Rails.application.routes.draw do
  resources :spies
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/spy.rb
class Spy < ApplicationRecord
     after_create_commit { broadcast_append_to('spies', target: 'spies', locals: { spy: self }) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/spies_controller.rb
class SpiesController < ApplicationController
  before_action :set_spy, only: %i[ show edit update destroy ]

  # GET /spies or /spies.json
  def index
    @spies = Spy.all
  end

  # GET /spies/1 or /spies/1.json
  def show
  end

  # GET /spies/new
  def new
    @spy = Spy.new
  end

  # GET /spies/1/edit
  def edit
  end

  # POST /spies or /spies.json
  def create
    @spy = Spy.new(spy_params)
  
    respond_to do |format|
      if @spy.save
        # Our addition
        format.turbo_stream { render turbo_stream: turbo_stream.replace("new_spy", partial: "spy_link")}
        format.html { redirect_to @spy, notice: "Spy was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @spy.errors, status: :unprocessable_entity }
      end
    end
  end
    

  # PATCH/PUT /spies/1 or /spies/1.json
  def update
    respond_to do |format|
      if @spy.update(spy_params)
        format.html { redirect_to spy_url(@spy), notice: "Spy was successfully updated." }
        format.json { render :show, status: :ok, location: @spy }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @spy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /spies/1 or /spies/1.json
  def destroy
    @spy.destroy!

    respond_to do |format|
      format.html { redirect_to spies_url, notice: "Spy was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_spy
      @spy = Spy.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def spy_params
      params.require(:spy).permit(:name, :mission)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/spies_helper.rb
module SpiesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HotwireSpies</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/spies/_form.html.erb
<%= form_with(model: spy) do |form| %>
  <% if spy.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(spy.errors.count, "error") %> prohibited this spy from being saved:</h2>

      <ul>
        <% spy.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :mission, style: "display: block" %>
    <%= form.text_field :mission %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/spies/_spy.html.erb
<%= turbo_frame_tag spy do %>
  <div>
    <%= spy.name %> | Current mission: <%= spy.mission %>
  </div>
<% end %>
  

app/views/spies/_spy_link.html.erb
<%= turbo_frame_tag "new_spy" do %>
  <%= link_to 'New Spy', new_spy_path %>
<% end %>
  

app/views/spies/edit.html.erb
<h1>Editing spy</h1>

<%= render "form", spy: @spy %>

<br>

<div>
  <%= link_to "Show this spy", @spy %> |
  <%= link_to "Back to spies", spies_path %>
</div>

app/views/spies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Spies</h1>

<%= turbo_stream_from "spies" %>
<div id="spies">
  <% @spies.each do |spy| %>
    <%= render spy, spy: spy %>
  <% end %>
</div>

<br>
<%= render "spy_link" %>
  

app/views/spies/new.html.erb
<%= turbo_frame_tag "new_spy" do %>
  <%= render 'form', spy: @spy %>
<% end %>
  

app/views/spies/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @spy %>

<div>
  <%= link_to "Edit this spy", edit_spy_path(@spy) %> |
  <%= link_to "Back to spies", spies_path %>

  <%= button_to "Destroy this spy", @spy, method: :delete %>
</div>